MVC/Models/ErrorViewModel.cs
namespace MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC/Controllers/DbController.cs
using DataAccess.Context;
using DataAccess.Entities;
using DataAccess.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MVC.Controllers
{
    public class DbController : Controller
    {
        private readonly Db _db;

        public DbController(Db db)
        {
            _db = db;
        }

        public IActionResult Seed()
        {
            #region Mevcut verilerin silinmesi

           

            var users = _db.Users.ToList();
            _db.Users.RemoveRange(users);

            var roles = _db.Roles.ToList();
            _db.Roles.RemoveRange(roles);

            if (roles.Count > 0) // eğer veritabanında rol kaydı varsa eklenecek rollerin rol id'lerini aşağıdaki SQL komutu üzerinden 1'den başlayacak hale getiriyoruz
                                 // eğer kayıt yoksa o zaman zaten rol tablosuna daha önce veri eklenmemiştir dolayısıyla rol id'leri 1'den başlayacaktır
            {
                _db.Database.ExecuteSqlRaw("dbcc CHECKIDENT ('Roles', RESEED, 0)"); // ExecuteSqlRaw methodu üzerinden istenilen SQL sorgusu elle yazılıp veritabanında çalıştırılabilir
            }

            var suppliers = _db.Suppliers.ToList();
            _db.Suppliers.RemoveRange(suppliers);

            var orderDetails = _db.OrderDetails.ToList();
            _db.OrderDetails.RemoveRange(orderDetails);

            var products = _db.Products.ToList();
            _db.Products.RemoveRange(products);

            var orders = _db.Orders.ToList();
            _db.Orders.RemoveRange(orders);

            var categories = _db.Categories.ToList();
            _db.Categories.RemoveRange(categories);

            #endregion

            #region İlk verilerin oluşturulması

            _db.Roles.Add(new Role()
            {
                RoleName = "Admin", // 1
            });

            _db.Roles.Add(new Role()
            {
                RoleName = "User", // 2
            });

            _db.SaveChanges();

            _db.Users.Add(new User()
            {
                Name = "GZD",
                Password = "GZD",
                RoleId = (int)Roles.Admin

            });
            _db.Users.Add(new User()
            {
                Name = "Gzd1",
                Password = "Gzd1",
                RoleId = (int)Roles.User


            });
            _db.SaveChanges();
            
            _db.Suppliers.Add(new Supplier()
            {
                Name = "X Firması",
                Description = "X Malzemeleri",
                Address = "Ankara",
                ContactNumber = 0000,
                
            });

            _db.Suppliers.Add(new Supplier()
            {
                Name = "Y Firması",
                Description = "Y Malzemeleri",
                Address = "İstanbul",
                ContactNumber = 1111,
                
            });

            _db.Suppliers.Add(new Supplier()
            {
                Name = "Z Firması",
                Description = "Z Malzemeleri",
                Address = "İzmir",
                ContactNumber = 2222,

            });

            _db.SaveChanges();

            _db.Categories.Add(new Category()
            {
                Name = "Komponent",
                Description = "elektronik bir cihazın çalışmasına yardımcı olan devre sistemi",
                Products = new List<Product>()
                {
                    new Product()
                    {
                        Name = "Kondansatör",
                        Description = "Kapasitesi: 1 uF - Gerilim: 50 V",
                        StockAmount = 1,
                        LotNo = 010101,
                        UnitPrice = 20,
                        SupplierId = _db.Suppliers.SingleOrDefault(s => s.Name == "X Firması").Id,
                        
                    },
                }
            }
            );
            _db.Categories.Add(new Category()
            {
                Name = "Sensör",
                Description = "elektronik bir cihazın çalışmasına yardımcı olan devre sistemi",
                Products = new List<Product>()
                {
                    new Product()
                    {
                        Name = "Sıcaklık/Nem",
                        Description = "Sıcaklık Sensörü - Sıcaklık Aralığı: -55 ile 150 derece",
                        StockAmount = 1,
                        LotNo = 010101,
                        UnitPrice = 20,
                        SupplierId = _db.Suppliers.SingleOrDefault(s => s.Name == "Y Firması").Id,

                                         
                    },
                }

            });
            _db.SaveChanges();

            _db.Orders.Add(new Order()
            {
                Situation = "Acil",
                Date = new DateTime(2024, 11, 11),
                Description = "X projesi için ",
                UserId = _db.Users.SingleOrDefault(u => u.Name == "GZD").Id,
                OrderDetails = new List<OrderDetail>()
                {
                   new OrderDetail()
                   {
                       ProductId = _db.Products.SingleOrDefault(p  => p.Name == "Sıcaklık/Nem").Id
                   }
                }

            });
            _db.Orders.Add(new Order()
            {
                Situation = "Standart",
                Date = new DateTime(2024, 10, 11),
                Description = "Stok için ",
                UserId = _db.Users.SingleOrDefault(u => u.Name == "Gzd1").Id,
                OrderDetails = new List<OrderDetail>()
                {
                   new OrderDetail()
                   {
                       ProductId = _db.Products.SingleOrDefault(p  => p.Name == "Kondansatör").Id
                   }
                }
            });

            _db.SaveChanges();
           

            #endregion

            return View();
        }
    }
}

MVC/Controllers/OrdersController.cs
#nullable disable

using Business.Models;
using Business.Services;
using Core.Results.Bases;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Security.Claims;

namespace MVC.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrdersController : Controller
    {
        private readonly IOrderService _orderService;
        private readonly IUserService _userService;
        private readonly IProductService _productService;

        public OrdersController(IOrderService orderService, IUserService userService = null, IProductService productService = null)
        {
            _orderService = orderService;
            _userService = userService;
            _productService = productService;
        }
        // GET: Orders

        //[Authorize] //Identity cookie var mı diye kontrol eder 
        //[Authorize(Roles = "Admin")] //Hem Identity cookie var mı diye hemde Identity cookie Admin rolü var mı diye kontrol eder 
        [AllowAnonymous]
        public IActionResult Index()
        {
            List<OrderModel> orderList = _orderService.Query().ToList(); 
            return View(orderList);
        }

        // GET: Orders/Details/5
        //[Authorize(Roles = "Admin")]
        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            OrderModel order = _orderService.Query().SingleOrDefault(o => o.Id == id);
            if (order == null)
            {
                return View("_Error", "Order not found!");
            }
            return View(order);
        }


        // GET: Orders/Create
        //[Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            //var userId = User.Claims.SingleOrDefault(c => c.Type == ClaimTypes.Sid).Value;
            //ViewData["UserId"] = new SelectList(_userService.Query().ToList(), "Id", "Name", userId);
            ViewData["Products"] = new MultiSelectList(_productService.Query().ToList(),"Id","Name");

            var model = new OrderModel()
            {
                UserId = Convert.ToInt32(User.Claims.SingleOrDefault(c => c.Type == ClaimTypes.Sid).Value)
            };
            return View(model);
        }

        // POST: Orders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "Admin")]

        public IActionResult Create(OrderModel order)
        {
            if (ModelState.IsValid)
            {
                order.UserId = Convert.ToInt32(User.Claims.SingleOrDefault(c => c.Type == ClaimTypes.Sid).Value);
                Result result = _orderService.Add(order);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }

                ModelState.AddModelError("", result.Message);
            }
            ViewData["UserId"] = new SelectList(_userService.Query().ToList(), "Id", "Name", order.UserId);
            ViewData["Products"] = new MultiSelectList(_productService.Query().ToList(), "Id", "Name", order.ProductIds);
            return View(order);
        }

        // GET: Orders/Edit/5
        //[Authorize(Roles = "Admin")]
        public IActionResult Edit(int id)
        {
            OrderModel order = _orderService.Query().SingleOrDefault(o => o.Id == id);
            if (order == null)
            {
                return View("_Error", "Order not found!");
            }


            ViewData["UserId"] = new SelectList(_userService.Query().ToList(), "Id", "Name", order.UserId);
            ViewData["Products"] = new MultiSelectList(_productService.Query().ToList(), "Id", "Name", order.ProductIds);
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "Admin")]
        public IActionResult Edit(OrderModel order)
        {
            if (ModelState.IsValid)
            {
                var result = _orderService.Update(order);

                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }

                ModelState.AddModelError("", result.Message);
            }

             ViewData["UserId"] = new SelectList(_userService.Query().ToList(), "Id", "Name", order.UserId);
             ViewData["Products"] = new MultiSelectList(_productService.Query().ToList(), "Id", "Name", order.ProductIds);
             return View(order);
        }

        // GET: Orders/Delete/5
        //[Authorize(Roles = "Admin")]
        public IActionResult Delete (int id)
        {
            Result result = _orderService.Delete(id);

            TempData["Message"] = result.Message;

            return RedirectToAction (nameof(Index));
        }

        //public IActionResult Delete(int id)
        //{
        //    OrderModel order = _orderService.Query().SingleOrDefault(o => o.Id == id);
            
        //    if(order == null)
        //    {
        //        return View("_Error", "Order not found!s");
        //    }
        //    return View(order);
        //}

        //// POST: Orders/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        ////[Authorize(Roles = "Admin")]
        //public IActionResult DeleteConfirmed(int id)
        //{
        //    Result result = _orderService.Delete(id);

        //    TempData["Message"] = result.Message;
        //    return RedirectToAction(nameof(Index));
        //}
    }
}

MVC/Controllers/SuppliersController.cs
#nullable disable

using Business.Models;
using Business.Services;
using Core.Results.Bases;
using DataAccess.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MVC.Controllers
{
    [Authorize(Roles = "Admin")]

    public class SuppliersController : Controller
    {
        private readonly ISupplierService _supplierService;

        public SuppliersController(ISupplierService supplierService)
        {
            _supplierService = supplierService;
        }

        // GET: Suppliers
        [AllowAnonymous]
        public IActionResult Index()
        {
            List<SupplierModel> suppliers = _supplierService.Query().ToList();
            return View(suppliers);
        }

        // GET: Suppliers/Details/5
        [AllowAnonymous]
        public IActionResult Details(int id)
        {
            SupplierModel supplier = _supplierService.Query().SingleOrDefault(s => s.Id == id);
            if (id == null)
            {
                return View("_Error", "Suplier not found!");
            }

            return View(supplier);
        }

        // GET: Suppliers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Suppliers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(SupplierModel supplier)
        {
            if(ModelState.IsValid)
            {
                Result result = _supplierService.Add(supplier);
                
                if(result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            return View(supplier);
            
        }

        // GET: Suppliers/Edit/5
        public IActionResult Edit(int id)
        {
            SupplierModel supplier = _supplierService.Query().SingleOrDefault(s => s.Id == id);
            if(supplier == null)
            {
                return View("_Error", "Supplier not found!");
            }
            return View(supplier);
        }

        // POST: Suppliers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(SupplierModel supplier)
        {
            if (ModelState.IsValid)
            {
                var result = _supplierService.Update(supplier);
                if (result.IsSuccessful)
                {
                    TempData["Message"] = result.Message;
                    return RedirectToAction(nameof(Index));
                }
                ModelState.AddModelError("", result.Message);
            }
            return View(supplier);
        }

        // GET: Suppliers/Delete/5
        public IActionResult Delete (int id)
        {
            Result result = _supplierService.Delete(id);

            TempData["Message"] = result.Message;

            return RedirectToAction (nameof(Index));
        }

        //public IActionResult Delete(int id)
        //{
        //    SupplierModel supplier = _supplierService.Query().SingleOrDefault(s => s.Id == id);

        //    if(supplier == null)
        //    {
        //        return View("_Error", "Supplier not found!");
        //    }
        //    return View(supplier);
        //}

        //// POST: Suppliers/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public IActionResult DeleteConfirmed(int id)
        //{
        //    Result result = _supplierService.Delete(id);

        //    TempData["Message"] = result.Message;

        //    return RedirectToAction(nameof(Index));
        //}
    }
}

MVC/Views/Shared/_Error.cshtml
@model string

@{
    ViewData["Title"] = "Error!";
}

<h1 class="text-danger">Error!</h1>
@if (string.IsNullOrWhiteSpace(Model))
{
    <h2 class="text-danger">An error occurred while processing your request.</h2>
}
else
{
    <p class="text-danger">@Model</p>
}

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | @AppSettings.Title</title>
    <!--font awesome icons (free version) -->  
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/_site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Report" asp-action="Index" asp-controller="Home">Report&nbsp;|&nbsp;</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Products">Products&nbsp;|&nbsp;</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Categories">Categories&nbsp;|&nbsp;</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Orders">Orders&nbsp;|&nbsp;</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-action="Index" asp-controller="Suppliers">Suppliers&nbsp;|&nbsp;</a>
                        </li>

                        @if (!User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Account" asp-action="Login" asp-controller="Users">Login&nbsp;|&nbsp;</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Account" asp-action="Register" asp-controller="Users">Register&nbsp;|&nbsp;</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-action="GetFavorites" asp-controller="Favorites">Favorites&nbsp;|&nbsp;</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Account" asp-action="Logout" asp-controller="Users">Logout&nbsp;|&nbsp;<span>@User.Identity.Name</span></a>
                                
                            </li>
                        }
                        @* <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Db" asp-action="Seed">Seed DB</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year | @AppSettings.Title <a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/_site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>